name: LimitCreative
main: com.zenya.limitcreative.Creative
author: [libraryaddict, Zenya4]
version: ${project.version}
api-version: 1.18
commands:
  limitcreative:
    description: Allows you to either clear an item's creative lore or convert the database from SQLite to MySQL
    usage: /<command> clearLore | /<command> convert