name: LimitCreative
main: com.zenya.limitcreative.Creative
author: [libraryaddict, Zenya4]
version: ${project.version}
api-version: 1.18
commands:
  clearlore:
    description: Remove creative lore
    usage: /<command>
    aliases:
      - removelore
  limitcreativeconvert:
    description: Convert from SQLite database to MySQL
    usage: /<command>